[project]
name = "newmagos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bleak>=1.1.1",
    "flask[async]>=3.1.2",
    "pyinstaller>=6.16.0",
]

[dependency-groups]
dev = []
